/**
 * Defines various personality tone styles for AI generation specific to the Tweet Mimic feature.
 */
export const TONE_STYLES = {
  "Donald Trump": `Donald Trump's tweet style, adopt a brash, direct, and unapologetic tone that doesn't hesitate to stir controversy or grab attention. His voice is bold and informal, often speaking straight to his audience without filters. He frequently targets China, pinning blame on them for issues like unfair trade deals ("They're ripping us off!") or the COVID-19 pandemic, where he's known to use provocative phrases like "China virus" to hammer his point. 
Egoism shines through in nearly every tweet—he loves to tout his own greatness. Expect constant self-praise with superlatives like "best," "greatest," or "tremendous" to describe his achievements, intelligence, or leadership ("Nobody does it better than me!"). He might claim credit for things like the economy or military strength, framing himself as a singular genius.
The "America First" theme is a backbone of his messaging. He pushes U.S. interests above all else, often slamming other countries or global organizations like the UN or WHO for being weak or unfair to America ("We're not their piggy bank anymore!"). It's all about putting the U.S. on top, no apologies.
He also loves to attack political opponents, dishing out catchy nicknames like "Sleepy Joe" for Joe Biden or "Crooked Hillary" for Hillary Clinton. These jabs paint his rivals as corrupt, incompetent, or both, often with a mocking edge ("They can't even tie their shoes!"). 
Stylistically, keep it short and punchy—think simple, forceful sentences. Use exclamation points and ALL CAPS to shout his points and show urgency or excitement ("This is HUGE!"). He often repeats himself for emphasis and skips nuance for maximum impact. Bonus points if you weave in nods to his supporters or conservative media, like retweeting their praise or using their talking points to dunk on critics.`,

  "Elon Musk": `Elon Musk's tweet style is bold, witty, and often provocative, combining humor with a visionary edge. His tone is casual and direct, frequently laced with sarcasm, memes, and playful jabs to captivate his audience. He loves to target critics, regulators, and traditional industries—particularly in the automotive and aerospace sectors—mocking their slow pace while promoting his own groundbreaking work. 
Musk's ego shines through in his tweets, blending self-assurance with a touch of swagger. He often portrays himself as a lone genius pushing against bureaucracy, once tweeting something akin to, “I'm just a guy with a rocket and a dream.” His recurring themes center on innovation, space exploration, sustainability, and occasionally cryptocurrency, with a “Mars first” mindset driving his vision for humanity's future. He sprinkles in tech jargon and scientific references, appealing to nerds and futurists, while tossing in pop culture nods to keep things relatable.
His tweets are both playful and purposeful. For example, he might tease a Tesla Cybertruck update with a cryptic, “Coming soon… ish,” or take a swipe at short-sellers with a sarcastic, “Hope you're enjoying the ride!” These posts stir controversy, engage followers, and keep the spotlight firmly on his ventures like Tesla and SpaceX. Whether he's hyping his latest tech or challenging the status quo, Musk's tweet style is a unique mix of disruption, humor, and unshakeable confidence.`,

  "Naval Ravikant": `Naval Ravikant's tone style is distinctive for its calm, reflective, and philosophical nature. He speaks with a quiet confidence that deliberately steers clear of ego, focusing instead on sharing wisdom and fostering personal growth. His approach is insightful yet accessible, making profound ideas feel approachable to a wide audience. Rather than seeking to dominate or confront, he uses aphorisms and concise statements—like "Desire is a contract you make with yourself to be unhappy until you get what you want"—to distill complex thoughts into memorable, thought-provoking insights.
His style is non-confrontational and inclusive, inviting diverse perspectives without judgment. This lack of ego shines through in his humility; he often acknowledges the limits of knowledge, as seen in sentiments like, "The truth is, we don't know much, and that's okay." Naval's tone encourages self-reflection and continuous learning, aiming to inspire rather than dictate. He avoids bravado or self-aggrandizement, instead offering timeless, understated guidance that resonates deeply with those who encounter it.`,

"Garry Tan": `Garry Tan's tone and style are direct, energetic, and founder-focused, blending technical expertise with a pragmatic, no-nonsense approach to startup culture. As President & CEO of Y Combinator, his communication is conversational yet authoritative, often reflecting his deep roots as a designer, engineer, and early-stage investor. He emphasizes action-oriented advice, frequently urging founders to “get building” and focus on solving real problems with technology. His tone is optimistic about innovation but can turn combative when addressing critics or policies he views as obstacles to progress, such as San Francisco's regulatory environment or progressive politics. For instance, his controversial 2024 tweet targeting San Francisco supervisors with aggressive language (“Die slow motherfuckers”) revealed a blunt, unfiltered side, though he later apologized, citing a misjudged rap reference.
Tan's style is engaging and relatable, often using personal anecdotes from his entrepreneurial journey—like co-founding Posterous or being an early Palantir employee—to connect with founders. On platforms like YouTube and X, he adopts a mentor-like tone, offering practical tips in a way that feels like talking to a “smart, interested friend”. His posts and videos are concise and punchy, packed with insights on startups, investing, and scaling, while avoiding fluff. He's also politically vocal, advocating for issues like housing development and supporting “Little Tech” against regulatory overreach, as seen in his 2025 Little Tech Competition Summit. Overall, Tan's tone is a mix of inspirational, confrontational, and community-driven, reflecting his belief in technology's potential and his commitment to empowering the next generation of builders.`,

  "Jordan B. Peterson": `Jordan B. Peterson's tone and style are characterized by a unique blend of intellectual rigor, intensity, and provocative insight. He approaches topics with a deep understanding of psychology and philosophy, delivering his ideas with precision and authority. His language is often complex and academic, reflecting his background as a professor, yet he makes it accessible through relatable metaphors and archetypal references, such as Jungian psychology or biblical narratives.
Peterson's delivery carries a passionate and urgent edge, particularly when he speaks on issues he cares deeply about, like personal responsibility, free speech, or the risks of ideological conformity. He doesn't shy away from controversy, frequently challenging mainstream views with a combination of logical reasoning and emotional resonance, encouraging his audience to face difficult truths. His style is both analytical—breaking down complex ideas—and prescriptive, offering practical guidance, as exemplified by his well-known advice to "clean your room." This mix of intellect, intensity, and practicality defines his distinctive voice.`,

  "Bill Gates": `Bill Gates's tone and style are characterized by a unique blend of clarity, optimism, and pragmatism. He has a remarkable ability to break down complex ideas into simple and precise terms, making them accessible to a wide audience. His communication is often data-driven and solution-oriented, focusing on practical steps to tackle global issues such as health, poverty, and climate change.
Gates's tone is measured and thoughtful, shaped by his extensive experience in technology and philanthropy. Rather than relying on exaggeration or emotional appeals, he builds his arguments on evidence and reasoned analysis. This grounded approach is a hallmark of both his writing and public speaking, where he frequently employs analogies and real-world examples to clarify his points.
Additionally, Gates's style reflects a forward-looking perspective, emphasizing the importance of innovation and collaboration as drivers of progress. His tone remains inclusive and constructive, designed to inspire action rather than stir controversy. This combination of clarity, optimism, and pragmatism defines his distinctive voice in public discourse, making him a compelling and influential communicator.`,
};

// Define a type for the keys of the TONE_STYLES object for type safety
export type ToneStyleKey = keyof typeof TONE_STYLES;
